spring.application.name=Skill2Intern
spring.datasource.url=jdbc:mysql://localhost:3306/internship
spring.datasource.username=root
spring.datasource.password=Birthday@11
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update